/* globals describe, it, expect, beforeAll */
const zapier = require('zapier-platform-core');

zapier.tools.env.inject(); // read from the .env file

const App = require('../index');

const appTester = zapier.createAppTester(App);

describe('oauth2 app', () => {
  beforeAll(() => {
    // It's a good idea to store your Client ID and Secret in the environment rather than in code.
    if (!(process.env.CLIENT_ID && process.env.CLIENT_SECRET)) {
      throw new Error(
        'Before running the tests, make sure CLIENT_ID and CLIENT_SECRET are available in the environment.',
      );
    }
  });

  it('generates an authorize URL', async () => {
    const bundle = {
      // In production, these will be generated by Zapier and set automatically
      inputData: {
        state: '4444',
        redirect_uri: 'https://zapier.com/',
      },
      environment: {
        CLIENT_ID: process.env.CLIENT_ID,
        CLIENT_SECRET: process.env.CLIENT_SECRET,
      },
    };

    const authorizeUrl = await appTester(
      App.authentication.oauth2Config.authorizeUrl,
      bundle,
    );

    expect(authorizeUrl).toBe(
      `https://cloud.ouraring.com/oauth/authorize?client_id=${process.env.CLIENT_ID}&state=4444&redirect_uri=https%3A%2F%2Fzapier.com%2F&response_type=code&scope=email%20daily`,
    );
  });
});
